"""
YOLOv8 Training Module for Package Damage Detection.
Supports model scaling (yolov8n, yolov8s, yolov8m), single-package dataset targeting,
automatic device detection, OOM recovery, and visualization artifact preservation.
"""

import os
import sys
import shutil
import argparse
from pathlib import Path
from typing import Dict, Any, Optional

# Add parent directory to sys.path
current_dir = Path(__file__).resolve().parent
project_root = current_dir.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.utils import (
    PROCESSED_DATA_DIR,
    WEIGHTS_DIR,
    RUNS_DIR,
    VISUALIZATIONS_DIR,
    detect_hardware,
    get_logger,
)

logger = get_logger("TrainYOLO")


def copy_training_visualizations(source_dir: Path, target_dir: Path):
    """
    Copies key visual evaluation plots generated by Ultralytics into outputs/visualizations/.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    plot_patterns = [
        "results.png",
        "confusion_matrix.png",
        "confusion_matrix_normalized.png",
        "PR_curve.png",
        "F1_curve.png",
        "P_curve.png",
        "R_curve.png",
        "val_batch*_pred*.jpg",
        "train_batch*.jpg",
    ]

    copied_count = 0
    for pattern in plot_patterns:
        for f in source_dir.glob(pattern):
            try:
                dest = target_dir / f.name
                shutil.copy2(f, dest)
                copied_count += 1
            except Exception as e:
                logger.warning(f"Could not copy {f.name}: {e}")

    logger.info(f"Copied {copied_count} training visualization artifacts to {target_dir}")


def train_damage_detector(
    data_yaml_path: Optional[Path] = None,
    model_size: str = "yolov8n.pt",  # 'yolov8n.pt', 'yolov8s.pt', 'yolov8m.pt'
    epochs: int = 50,
    imgsz: int = 640,
    patience: int = 15,
    initial_batch: int = -1,
    run_name: str = "package_damage_run",
    output_weight_name: str = "best.pt",
) -> Path:
    """
    Trains YOLOv8 model on the dataset with robust OOM fallback handling.
    Saves and returns the path to best model in models/weights/.
    """
    from ultralytics import YOLO

    if data_yaml_path is None:
        data_yaml_path = PROCESSED_DATA_DIR / "dataset.yaml"

    if not data_yaml_path.exists():
        raise FileNotFoundError(
            f"Dataset configuration not found at {data_yaml_path}. "
            "Please run dataset inspection first."
        )

    # Hardware detection
    hw_info = detect_hardware()
    device = hw_info["recommended_device"]
    logger.info(f"Hardware setup: PyTorch={hw_info['pytorch_version']}, CUDA={hw_info['cuda_available']}, Device={device}")

    # Ensure output directories
    WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)
    RUNS_DIR.mkdir(parents=True, exist_ok=True)

    # Batch sizes to attempt on failure
    if device == "cpu":
        batch_candidates = [16, 8, 4]
    else:
        batch_candidates = [-1, 16, 8, 4]

    trained_best_path = None
    save_run_dir = None

    for batch_size in batch_candidates:
        try:
            logger.info(
                f"Starting YOLOv8 training: model={model_size}, epochs={epochs}, "
                f"imgsz={imgsz}, batch={batch_size}, device={device}, data={data_yaml_path.name}"
            )

            # Initialize YOLOv8 model
            model = YOLO(model_size)

            results = model.train(
                data=str(data_yaml_path),
                epochs=epochs,
                imgsz=imgsz,
                batch=batch_size,
                patience=patience,
                device=device,
                project=str(RUNS_DIR / "train"),
                name=run_name,
                exist_ok=True,
                verbose=True,
                save=True,
                plots=True,
                workers=0 if os.name == "nt" else 4,
            )

            save_run_dir = Path(model.trainer.save_dir) if hasattr(model, "trainer") and model.trainer else (RUNS_DIR / "train" / run_name)
            candidate_best = save_run_dir / "weights" / "best.pt"

            if candidate_best.exists():
                final_best_dest = WEIGHTS_DIR / output_weight_name
                shutil.copy2(candidate_best, final_best_dest)
                trained_best_path = final_best_dest
                logger.info(f"Training succeeded! Best model saved to {final_best_dest}")
                break
            else:
                candidate_last = save_run_dir / "weights" / "last.pt"
                if candidate_last.exists():
                    final_best_dest = WEIGHTS_DIR / output_weight_name
                    shutil.copy2(candidate_last, final_best_dest)
                    trained_best_path = final_best_dest
                    logger.info(f"Training completed. Model saved to {final_best_dest}")
                    break

        except RuntimeError as e:
            err_str = str(e).lower()
            if "out of memory" in err_str or "cuda" in err_str:
                logger.warning(f"CUDA Out-of-Memory / Runtime error with batch={batch_size}. Retrying with smaller batch size...")
                continue
            else:
                logger.error(f"Training encountered RuntimeError: {e}", exc_info=True)
                raise e
        except Exception as e:
            logger.error(f"Training failed with error: {e}", exc_info=True)
            raise e

    if trained_best_path is None or not trained_best_path.exists():
        raise RuntimeError("Training failed to produce a valid best.pt model file.")

    # Copy visualization artifacts
    if save_run_dir and save_run_dir.exists():
        copy_training_visualizations(save_run_dir, VISUALIZATIONS_DIR)

    return trained_best_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--single-package", action="store_true", help="Train on Single Package Dataset")
    parser.add_argument("--model", type=str, default="yolov8n.pt", help="YOLOv8 model size (yolov8n.pt, yolov8s.pt, yolov8m.pt)")
    parser.add_argument("--epochs", type=int, default=50, help="Number of epochs")
    parser.add_argument("--batch", type=int, default=16, help="Batch size")
    args = parser.parse_args()

    data_cfg = PROCESSED_DATA_DIR / ("single_package_dataset.yaml" if args.single_package else "dataset.yaml")
    out_name = "best_single_package.pt" if args.single_package else "best.pt"
    r_name = "single_package_run" if args.single_package else "package_damage_run"

    best_model = train_damage_detector(
        data_yaml_path=data_cfg,
        model_size=args.model,
        epochs=args.epochs,
        initial_batch=args.batch,
        run_name=r_name,
        output_weight_name=out_name,
    )
    print(f"Training finished. Best model at: {best_model}")
