"""
Training Module for Stage 1 Individual Package Detector.
Trains YOLOv8 specifically to detect individual packages/boxes/parcels in multi-package scenes.
Saves model to models/weights/package_detector_best.pt without overwriting damage detector.
"""

import os
import sys
import shutil
import argparse
from pathlib import Path
from typing import Dict, Any, Optional

# Add parent directory to sys.path
current_dir = Path(__file__).resolve().parent
project_root = current_dir.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.utils import (
    PROCESSED_DATA_DIR,
    WEIGHTS_DIR,
    RUNS_DIR,
    OUTPUTS_DIR,
    detect_hardware,
    get_logger,
)

logger = get_logger("TrainPackageDetector")
PACKAGE_OUTPUTS_DIR = OUTPUTS_DIR / "package_detector"


def copy_detector_visualizations(source_dir: Path, target_dir: Path):
    """
    Copies evaluation charts generated by Ultralytics into outputs/package_detector/.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    plot_patterns = [
        "results.png",
        "confusion_matrix.png",
        "confusion_matrix_normalized.png",
        "PR_curve.png",
        "F1_curve.png",
        "P_curve.png",
        "R_curve.png",
        "val_batch*_pred*.jpg",
        "train_batch*.jpg",
    ]

    copied = 0
    for pattern in plot_patterns:
        for f in source_dir.glob(pattern):
            try:
                shutil.copy2(f, target_dir / f.name)
                copied += 1
            except Exception as e:
                logger.warning(f"Could not copy {f.name}: {e}")

    logger.info(f"Copied {copied} package detector artifacts to {target_dir}")


def train_package_detector(
    data_yaml_path: Optional[Path] = None,
    model_size: str = "yolov8n.pt",
    epochs: int = 50,
    imgsz: int = 640,
    patience: int = 15,
    initial_batch: int = 16,
) -> Path:
    """
    Trains Stage 1 Package Detector and saves weights to models/weights/package_detector_best.pt.
    """
    from ultralytics import YOLO

    if data_yaml_path is None:
        data_yaml_path = PROCESSED_DATA_DIR / "package_detector_dataset.yaml"

    if not data_yaml_path.exists():
        raise FileNotFoundError(f"Package detector dataset config not found at {data_yaml_path}.")

    hw_info = detect_hardware()
    device = hw_info["recommended_device"]
    logger.info(f"Hardware setup: PyTorch={hw_info['pytorch_version']}, CUDA={hw_info['cuda_available']}, Device={device}")

    WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)
    PACKAGE_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

    batch_candidates = [initial_batch, 8, 4] if device == "cpu" else [-1, 16, 8, 4]
    run_name = "package_detector_run"
    trained_best_path = None
    save_run_dir = None

    for batch_size in batch_candidates:
        try:
            logger.info(
                f"Starting Package Detector training: model={model_size}, epochs={epochs}, "
                f"imgsz={imgsz}, batch={batch_size}, device={device}"
            )

            model = YOLO(model_size)
            results = model.train(
                data=str(data_yaml_path),
                epochs=epochs,
                imgsz=imgsz,
                batch=batch_size,
                patience=patience,
                device=device,
                project=str(RUNS_DIR / "train"),
                name=run_name,
                exist_ok=True,
                verbose=True,
                save=True,
                plots=True,
                workers=0 if os.name == "nt" else 4,
            )

            save_run_dir = Path(model.trainer.save_dir) if hasattr(model, "trainer") and model.trainer else (RUNS_DIR / "train" / run_name)
            candidate_best = save_run_dir / "weights" / "best.pt"

            if candidate_best.exists():
                final_dest = WEIGHTS_DIR / "package_detector_best.pt"
                shutil.copy2(candidate_best, final_dest)
                trained_best_path = final_dest
                logger.info(f"Package detector training succeeded! Best weights saved to {final_dest}")
                break
            else:
                candidate_last = save_run_dir / "weights" / "last.pt"
                if candidate_last.exists():
                    final_dest = WEIGHTS_DIR / "package_detector_best.pt"
                    shutil.copy2(candidate_last, final_dest)
                    trained_best_path = final_dest
                    logger.info(f"Package detector weights saved to {final_dest}")
                    break

        except RuntimeError as e:
            err_str = str(e).lower()
            if "out of memory" in err_str or "cuda" in err_str:
                logger.warning(f"OOM encountered with batch={batch_size}. Retrying smaller batch...")
                continue
            else:
                logger.error(f"Package detector training runtime error: {e}")
                raise e
        except Exception as e:
            logger.error(f"Package detector training error: {e}")
            raise e

    if trained_best_path is None or not trained_best_path.exists():
        raise RuntimeError("Package detector training failed to produce weights.")

    if save_run_dir and save_run_dir.exists():
        copy_detector_visualizations(save_run_dir, PACKAGE_OUTPUTS_DIR)

    return trained_best_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str, default="yolov8n.pt")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch", type=int, default=16)
    args = parser.parse_args()

    train_package_detector(model_size=args.model, epochs=args.epochs, initial_batch=args.batch)
